USE DARSHAN


CREATE TABLE SALES_DATA
(	
	REGION VARCHAR(25),
	PRODUCT VARCHAR(10),
	SALES_AMOUNT INT,
	SALES_YEAR DATETIME
)

INSERT INTO SALES_DATA(REGION , PRODUCT , SALES_AMOUNT , SALES_YEAR)
VALUES	('NORTH AMERICA','WATCH',1500,'2023'),
		('EUROPE','MOBILE',1200,'2023'),
		('ASIA','WATCH',1800,'2023'),
		('NORTH AMERICA','TV',900,'2024'),
		('EUROPE','WATCH',2000,'2024'),
		('ASIA','MOBILE',1000,'2024'),
		('NORTH AMERICA','MOBILE',1600,'2023'),
		('EUROPE','TV',1500,'2023'),
		('ASIA','TV',1100,'2024'),
		('NORTH AMERICA','WATCH',1700,'2024')


-- Part – A:


-- 1. Display Total Sales Amount by Region.
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
FROM SALES_DATA
GROUP BY REGION

-- 2. Display Average Sales Amount by Product
SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVERAGE_AMOUNT
FROM SALES_DATA
GROUP BY PRODUCT

-- 3. Display Maximum Sales Amount by Year
SELECT SALES_YEAR, MAX(SALES_AMOUNT) AS MAXIMUM_AMOUNT
FROM SALES_DATA
GROUP BY SALES_YEAR

-- 4. Display Minimum Sales Amount by Region and Year
SELECT REGION,SALES_YEAR,MIN(SALES_AMOUNT) AS MININUM
FROM SALES_DATA
GROUP BY REGION,SALES_YEAR

-- 5. Count of Products Sold by Region
SELECT REGION, COUNT(PRODUCT) AS TOTAL_PRODUCT
FROM SALES_DATA
GROUP BY REGION

-- 6. Display Sales Amount by Year and Product
SELECT PRODUCT,SALES_YEAR,SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
FROM SALES_DATA
GROUP BY PRODUCT,SALES_YEAR

-- 7. Display Regions with Total Sales Greater Than 5000
SELECT REGION, SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
FROM SALES_DATA
GROUP BY REGION
HAVING SUM(SALES_AMOUNT)>5000

-- 8. Display Products with Average Sales Less Than 10000
SELECT PRODUCT, AVG(SALES_AMOUNT) AS AVERAGE_AMOUNT
FROM SALES_DATA
GROUP BY PRODUCT
HAVING AVG(SALES_AMOUNT)<10000

-- 9. Display Years with Maximum Sales Exceeding 500
SELECT SALES_YEAR, MAX(SALES_AMOUNT) AS MAXIMUM_AMOUNT
FROM SALES_DATA
GROUP BY SALES_YEAR
HAVING MAX(SALES_AMOUNT) > 500

-- 10. Display Regions with at Least 3 Distinct Products Sold.
SELECT REGION, COUNT(DISTINCT PRODUCT) AS TOTAL_PRODUCT
FROM SALES_DATA
GROUP BY REGION
HAVING COUNT(DISTINCT PRODUCT)>=3

-- 11. Display Years with Minimum Sales Less Than 1000
SELECT SALES_YEAR, MIN(SALES_AMOUNT) AS MINIMUM_AMOUNT
FROM SALES_DATA
GROUP BY SALES_YEAR
HAVING MIN(SALES_AMOUNT)<1000

-- 12. Display Total Sales Amount by Region for Year 2023, Sorted by Total Amount
SELECT REGION,SUM(SALES_AMOUNT) AS TATAL_AMOUNT
FROM SALES_DATA
WHERE SALES_YEAR = '2023'
GROUP BY REGION
ORDER BY SUM(SALES_AMOUNT)


