-- Part – B:


-- 1. Display Count of Orders by Year and Region, Sorted by Year and Region
SELECT SALES_YEAR,REGION, COUNT(PRODUCT) AS TOATL_PRODUCT
FROM SALES_DATA
GROUP BY SALES_YEAR, REGION
ORDER BY SALES_YEAR,REGION

-- 2. Display Regions with Maximum Sales Amount Exceeding 1000 in Any Year, Sorted by Region
SELECT REGION, SALES_YEAR , MAX(SALES_AMOUNT) AS MAXIMUM_AMOUNT
FROM SALES_DATA
GROUP BY REGION, SALES_YEAR
HAVING MAX(SALES_AMOUNT)>1000
ORDER BY REGION

-- 3. Display Years with Total Sales Amount Less Than 1000, Sorted by Year Descending
SELECT SALES_YEAR , SUM(SALES_AMOUNT) AS MAXIMUM_AMOUNT
FROM SALES_DATA
GROUP BY SALES_YEAR
HAVING SUM(SALES_AMOUNT)<1000
ORDER BY SALES_YEAR DESC

-- 4. Display Top 3 Regions by Total Sales Amount in Year 2024
SELECT TOP 3 REGION , SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
FROM SALES_DATA
WHERE SALES_YEAR = '2024'
GROUP BY REGION


-- Part – C:


-- 1. Display Products with Average Sales Amount Between 1000 and 2000, Ordered by Product Name
SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVERAGE_AMOUNT
FROM SALES_DATA
GROUP BY PRODUCT
HAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000
ORDER BY PRODUCT

-- 2. Display Years with More Than 5 Orders from Each Region
SELECT REGION, SALES_YEAR 
FROM SALES_DATA
GROUP BY REGION, SALES_YEAR
HAVING COUNT(PRODUCT) > 5

-- 3. Display Regions with Average Sales Amount Above 1500 in Year 2023 sort by amount in descending.
SELECT REGION , AVG(SALES_AMOUNT) AS AVERAGE_AMOUNT
FROM SALES_DATA
WHERE SALES_YEAR = '2023'
GROUP BY REGION
HAVING AVG(SALES_AMOUNT) > 1500 
ORDER BY AVG(SALES_AMOUNT)

-- 4. Find out region wise duplicate product.
SELECT REGION, COUNT(PRODUCT)
FROM SALES_DATA
GROUP BY REGION

--5. Find out region wise highest sales amount
SELECT REGION, MAX(SALES_AMOUNT) AS MAXIMUM_AMOUNT
FROM SALES_DATA
GROUP BY REGION
