---CREATE DATABASE DARSHAN

USE DARSHAN 


CREATE TABLE BRANCH
(	BNAME VARCHAR(50),
	CITY VARCHAR(50)
)

INSERT INTO BRANCH VALUES ('VRCE','NAGPUR'),('AJNI','NAGPUR'),('KAROLBAGH','DELHI'),
('CHANDI','DELHI'),('DHARAMPETH','NAGPUR'),('M.G.ROAD','BANGLORE'),
('ANDHERI','BOMBAY'),('VIRAR','BOMBAY'),('NEHRU PLACE','DELHI'),('POWAI','BOMBAY')