USE DARSHAN

CREATE TABLE CUSTOMERS
(	CNAME VARCHAR(50),
	CITY VARCHAR(50)
)

INSERT INTO CUSTOMERS(CNAME,CITY)
VALUES	('ANIL','CALCUTTA'),
		('SUNIL','DELHI'),
		('MEHUL','BARODA'),
		('MADHURI','PATNA'),
		('PRAMOD','NAGPUR'),
		('SANDIP','SURAT'),
		('SHIVANI','BOMBAY'),
		('KRANTI','BOMBAY'),
		('NAREN','BOMBAY')